import { defineConfig, devices } from "@playwright/test";

/**
 * bull-terra Playwright config.
 * - Specs live under tests/gen/<project>/ (generated by /gen-tests).
 * - Trace/screenshot/video on failure power the "real bug vs wrong test case"
 *   triage in the dashboard (PRD §9).
 * - global-setup logs in once and saves storageState to auth.json so generated
 *   specs start authenticated (PRD §14).
 */
export default defineConfig({
  testDir: "./tests/gen",
  fullyParallel: false, // v1 runs one suite at a time locally
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: process.env.CI ? "github" : "list",
  globalSetup: "./tests/global-setup.ts",

  use: {
    baseURL: process.env.BASE_URL,
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    // Reuse the logged-in state captured by global-setup, when present.
    storageState: process.env.BULL_TERRA_STORAGE_STATE || undefined,
  },

  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
});
